// <auto-generated />
namespace DonaldsonMotorsThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addjobtypes2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addjobtypes2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806021752587_addjobtypes2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
